DELETE  http://localhost:8080/event/8/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImhhcmRpa0BnbWFpbC5jb20iLCJleHAiOjE3NzAwMzI0OTEsInVzZXJfaWQiOjF9.YkfQW9fgsLVWJh--UVpu1KeD0XqEFw-wWM78pwZvt00