POST http://localhost:8080/event/3/register
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIyQGdtYWlsLmNvbSIsImV4cCI6MTc3MDAyNzgxMSwidXNlcl9pZCI6Mn0.dN5jb7FT50G_3E5iWoingsZPmU87_1eIHBaS9mP3lwk

